### ISSUE TITLE
There is no  size_config.dart in repository

### ISSUE THREAD

**Issue by behiunforgiven** [quiet-programmer/wp_blog_app#7]
The source has error and can not find size_config.dart file.

**Comment by sudo-which-qp** [comment]
the file was ignored... will be added now

**Comment by LebToki** [comment]
just wondering ....when now == taken place ?

**Comment by sudo-which-qp** [comment]
> just wondering ....when now == taken place ?

will be pushing it now

**Comment by sudo-which-qp** [comment]
> The source has error and can not find size_config.dart file.

sorry for the delay... pushing the size config file now... was doing some refactoring
